#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
go_to () {
	cd "$SCRIPT_DIR/archinstoo" || exit 1
}

pre_build () {
    rm -f ./*-any.pkg.tar.zst
}

clean () {
    rm -rf pkg src dist build ./*.egg-info ../*.egg-info 
}

sign () {
    gpg --detach-sign archinstoo-*.pkg.tar.zst
}

for i in "$@"; do
	case $i in
        -t | --tree)
        shift
        go_to
        {
            echo '# Project Structure'
            echo '```'
            tree -I '*.po|*.pyc|*.mo|*.png|*.svg|locales|docs|__pycache__|__init__.py'
            echo '```'
        } > docs/readme.md
        exit 0
        ;;
        -c | --clean)
        shift
        go_to
        clean
        exit 0
        ;;
        -b | --build)
        shift
        go_to
        pre_build
        makepkg -Cf
        sign
        clean
        exit 0
        ;;
        -v|venv)
        shift
        ./RUN
        exit 0
        ;;
        *)
        # Catch all with options also to local
        go_to
        python -B -m archinstall "$@"
        exit 0
        ;;
	esac
done

# No arguments - run local archinstall directly
go_to && python -B -m archinstall