#!/bin/bash
# shellcheck disable=SC1091,SC2154

. ./PKGBUILD && sudo pacman -S --needed "${depends[@]}"
cd archinstoo || exit 1

# update deps launch venv and run archinstall
if [ ! -d ".venv" ]; then
    python -m venv --system-site-packages .venv
    . .venv/bin/activate
    pip install -e .
else
    . .venv/bin/activate
fi

sudo .venv/bin/python -B -m archinstall "$@"
