#!/bin/bash
# shellcheck disable=SC1091,SC2154
ELEV="${ELEV:-sudo}"
# help / list / size 
# do not need root but we append it for most features
# can be launched with ELEV=doas env var
(cd archinstoo && "$ELEV" python -B -m archinstall "$@")