#!/bin/bash
# shellcheck disable=SC1091,SC2154
ELEV="${ELEV:-sudo}"
cd archinstoo || exit 1

# launch venv and run archinstall

if [ ! -d ".venv" ]; then
    python -m venv --system-site-packages .venv
    . .venv/bin/activate
    pip install -e .
else
    . .venv/bin/activate
fi

"$ELEV" .venv/bin/python -B -m archinstoo "$@"
