#!/bin/bash
# shellcheck disable=SC1091,SC2154
cd installer || exit 1

if [ ! -d ".venv" ]; then
	python -m venv --system-site-packages .venv
	. .venv/bin/activate
	pip install -e .
else
	. .venv/bin/activate
fi

.venv/bin/python -B -m archinstoo "$@"
