on: [push]
name: Other tools (track-only)
jobs:
    import-linter:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
            - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
              with:
                python-version: '3.14'
            - run: pip install import-linter
            - name: Check for circular imports (SCC) Syblings Check
              continue-on-error: true
              working-directory: archinstoo
              run: lint-imports
    vulture:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
            - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
              with:
                python-version: '3.14'
            - run: pip install vulture
            - name: Check for dead code
              continue-on-error: true
              working-directory: archinstoo
              run: vulture archinstoo
