on:
    push:
        # docs-only pushes, docs.yaml covers those
        paths-ignore:
            - '**.md'
            - mkdocs.yaml
            - .github/overrides/**
            - .github/docs-requirements.txt
name: Pytest test validation
permissions: {}
jobs:
    pytest:
        runs-on: ubuntu-latest
        container:
            image: archlinux/archlinux:latest@sha256:a502472374201ccf8301835475e40c4f0d4f11b02b9b34e5a74b513b8ed7d8c6
            options: --privileged
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                persist-credentials: false
            - name: Prepare arch
              run: |
                pacman-key --init
                pacman --noconfirm -Sy archlinux-keyring
                pacman --noconfirm -Syyu
                pacman --noconfirm -Sy python-pip python-pyparted pkgconfig gcc
            - run: pip install --break-system-packages --upgrade pip
            - name: Install archinstoo dependencies
              run: pip install --break-system-packages ./installer[dev]
            - name: Test with pytest
              run: pytest -c installer/pyproject.toml installer/tests
