name: Build archinstoo

on:
  push:
    # docs-only pushes, docs.yaml covers those
    paths-ignore:
      - '**.md'
      - mkdocs.yaml
      - .github/overrides/**
      - .github/docs-requirements.txt

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest@sha256:67f575e6ae9319883231be5e32468bb88d4afcfab281b5ac014bd03f0571f3bc
      options: --privileged
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Prepare arch
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
          pacman --noconfirm -Syyu
          pacman --noconfirm -Sy python-setuptools python-pip python-build
          pacman --noconfirm -Sy python-pyparted
      - name: Remove existing archinstall (if any)
        run: pip uninstall -y archinstoo --break-system-packages || true
      - name: Build archinstoo
        run: python -m build --wheel installer
      - name: Install archinstoo
        run: pip install installer/dist/*.whl --break-system-packages --no-deps
      - name: Run archinstoo
        run: |
          python -V
          archinstoo --help
      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: archinstoo
          path: installer/dist/*
